### ISSUE TITLE
Add UI support for control strategy recommendations

### ISSUE THREAD

**Issue by kenmeacham** [Spyderisk/system-modeller#128]
Issue #67 describes the new API for getting control strategy recommendations.

We then need to update the Spyderisk GUI to do the following:

- [x] Add button to launch the recommendations (i.e. call the API)
- [x] Monitor progress of the recommendations task (as this is potentially a long-running process)
- [x] Display the results

The exact displaying of results is to be decided. Initially we could simply display the JSON response, but it is likely that we will need some kind of widget to list the proposed control strategies, etc.

**Comment by panositi** [comment]
In the particular example the consequences list is null because it only shows consequences higher than Medium.

A recommendation includes an identifier (number), a list of CSG, a list of CS to be activated along with affected assets, and a state (risk calculation).

Maybe  we can skip presenting the CSG if the link of CS is directly browsable?

**Comment by scp93ch** [comment]
> Maybe we can skip presenting the CSG if the link of CS is directly browsable?

Did you mean "link to CSG"? Meaning we could list the CSGs and click through to the CSG explorer?

**Comment by scp93ch** [comment]
I think that the recommendations should be ordered by the risk vector.

For each recommendation, I would then want to be able to see a list of the CSGs that are involved. We present the CSGs because they have useful descriptions so you can get a feel for what is being suggested. Perhaps we present a list of CSGs using their descriptions and clickable so that the CSG explorer is opened on click. I think there should be a simple button to "Accept" a recommendation which then set all the Control Sets. I think it would also be useful to be able to see a list of the Control Sets for a recommendation, but perhaps that is hidden by default?

We need to take into account that the recommendation should be able to return that one or more Control Sets and CSGs should be disabled. That could simply be done by prepending the CSG or CS with "Add" or "Remove" or "+"/"-". We need to adjust the JSON to be able to hold that info though.

**Comment by mike1813** [comment]
Recommending that CSGs be deselected may be tricky. You may only need to disable one control set to disable a CSG, but which one? We certainly shouldn't deselect all the controls because some may be playing a useful role in some other CSG. Bottom line: it seems likely that to support CSG deselection (i.e., to support recommendations to reduce control side effects) we would need the search algorithm to search over combinations of control sets, not combinations of CSGs...

**Comment by scp93ch** [comment]
We discussed this further this morning.

For each recommendation we agreed that you'd want a button you could press to implement the recommendation in full, but that you'd also want to understand what was being proposed.

The list of CSGs provides a good overview of what is being proposed but in addition a list of Control Sets provides the detail (the list of CSGs does not explain everything, in particular if there are optional Control Sets that have not been included).

So building on the suggestions above, for a recommendation we should have a list of CSGs, with each CSG clickable to open the CSG explorer with just that one CSG shown (just as we get when clicking on a CSG in the Threat Explorer). I would suggest that initially we just use the CSG label (e.g. "SomeGreatCSG") but that ideally we'd append the list of assets that are involved (e.g. "SecureBIOS (server1)") so that if the same CSG appears more than once in the list then you can see which one is which and it doesn't look like a mistake.

I'd suggest that after the CSG list we have a CS list but that the CS list is initially collapsed so that it is only opened if the user wants to see the detail.

Maybe make each section expand/collapse but have the CSG ones expanded by default and the CS ones collapsed?

When we get to having the recommendation algorithm also returning a list of CSGs and CS to reactivate then these elements can simply be added as additional parts to this proposed display so that you end up with e.g.

```
Recommendation #1 

Resulting risk level High (0/3/123/1234/1234)

(-) Control Strategies to activate
* X
* Y
* Z
(+) Controls to activate
(-) Control Strategies to disable
* A
(+) Controls to disable
```

**Comment by scp93ch** [comment]
Following a demo of the current status there are a few suggestions:

1. Change the "select all recommendation controls" checkbox to a button. I would suggest a button labelled "Apply" (or "Implement", see previous comment).
2. The recommendation index in the JSON is not useful in this display and as we are sorting by risk vector the indices are not in order and just look weird. I think it is useful to have them numbered, but let's just number them in order of display after they are sorted.
3. The risk vector display is useful, but the "VH" etc labels currently there for debugging are problematic as it's a label that's hard-coded in the client and depends on the domain model. How about just listing the numbers (see comment above)? We could colour the numbers as well to indicate the risk level they apply to. Add a tooltip to the number display if it needs more explanation?
4. "Current risk level" display at the top is static text from the JSON report. This means that it remains the same even when the risk is recalculated and therefore can get out of date. Suggest just removing it.
5. It's not a bad idea to add "(beta)" to the Recommendation Explorer pop-up title as someone suggested!
6. I'd suggest the text in the comment above rather than just "Control Strategies" and "Controls". By adding "to activate" it explains more about what is proposed and leads in to the future case where we will display CS and CSG to deactivate.

**Comment by kenmeacham** [comment]
>     4. The "Current risk level" display at the top is static text from the JSON report. This means that it remains the same even when the risk is recalculated and therefore can get out of date. Suggest just removing it.

Given that we are displaying data from the recommendations report, rather than something dynamic, perhaps we could say "Starting risk level" rather than "Current risk level". Otherwise "Initial risk level"?

**Comment by scp93ch** [comment]
> > ```
> > 4. The "Current risk level" display at the top is static text from the JSON report. This means that it remains the same even when the risk is recalculated and therefore can get out of date. Suggest just removing it.
> > ```
> 
> Given that we are displaying data from the recommendations report, rather than something dynamic, perhaps we could say "Starting risk level" rather than "Current risk level". Otherwise "Initial risk level"?

I'm not sure what the value of the information is which is why I suggested to remove it. Why would I be interested to know the risk level at the point of requesting a recommendation? If I haven't applied any recommendation then I can see the risk level (if I'm interested) at the top right of the screen. If I have applied a recommendation (or done something else) and recalculated the risk then the whole recommendation explorer display is out of date. Why would I then want to see the risk level from before?

**Comment by kenmeacham** [comment]
> > > ```
> > > 4. The "Current risk level" display at the top is static text from the JSON report. This means that it remains the same even when the risk is recalculated and therefore can get out of date. Suggest just removing it.
> > > ```
> > 
> > 
> > Given that we are displaying data from the recommendations report, rather than something dynamic, perhaps we could say "Starting risk level" rather than "Current risk level". Otherwise "Initial risk level"?
> 
> I'm not sure what the value of the information is which is why I suggested to remove it. Why would I be interested to know the risk level at the point of requesting a recommendation? If I haven't applied any recommendation then I can see the risk level (if I'm interested) at the top right of the screen. If I have applied a recommendation (or done something else) and recalculated the risk then the whole recommendation explorer display is out of date. Why would I then want to see the risk level from before?

OK - will remove it then.

**Comment by kenmeacham** [comment]
>     3. The risk vector display is useful, but the "VH" etc labels currently there for debugging are problematic as it's a label that's hard-coded in the client and depends on the domain model. To resolve this we could just list the numbers (see comment above)? We could colour the numbers as well to indicate the risk level they apply to. Perhaps add a tooltip to the number display if it needs more explanation?

Yes, the short labels were only really intended to display for dev/debugging purposes (and helped to identify the sorting issue).

I don't think it's very clear for the user to see just a list of numbers. The labels (e.g. "Very High") are available from the domain model definitions, so can be used without any hardwiring. I would therefore suggest a tooltip that is displayed when you hover over the level label. See example (with before and after display). OK?

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/01043366-84a4-4031-8a92-c27a22bdc487)

**Comment by scp93ch** [comment]
> I don't think it's very clear for the user to see just a list of numbers. The labels (e.g. "Very High") are available from the domain model definitions, so can be used without any hardwiring. I would therefore suggest a tooltip that is displayed when you hover over the level label. See example (with before and after display). OK?

Yes the tooltip like that is what I was hoping for - that's good. The point though is what the tooltip is over. If you keep the "VH" type strings then we are hard-coding abbreviations of terms from a particular domain model. That's why I suggested just using the numbers (with a tooltip).

In principle we always try to avoid specialising the client to a particular domain model.

**Comment by kenmeacham** [comment]
> > I don't think it's very clear for the user to see just a list of numbers. The labels (e.g. "Very High") are available from the domain model definitions, so can be used without any hardwiring. I would therefore suggest a tooltip that is displayed when you hover over the level label. See example (with before and after display). OK?
> 
> Yes the tooltip like that is what I was hoping for - that's good. The point though is what the tooltip is over. If you keep the "VH" type strings then we are hard-coding abbreviations of terms from a particular domain model. That's why I suggested just using the numbers (with a tooltip).
> 
> In principle we always try to avoid specialising the client to a particular domain model.

Just to be clear, the hardwired "VH", etc will be removed. The tooltip uses info directly from the domain model, e.g. "Medium", which is what you hover over.

**Comment by scp93ch** [comment]
> Just to be clear, the hardwired "VH", etc will be removed. The tooltip uses info directly from the domain model, e.g. "Medium", which is what you hover over.

Sorry, I understand now, and of course you provided a screenshot but for some reason I thought the tooltip was just obscuring the list of numbers - sorry. So you are removing the list of risk-level count numbers entirely because it isn't clear to the user what they mean, and replacing it with the numbers fully explained but hidden in a tooltip.

I was thinking we'd have just the list of numbers `(1/3/56/789/4567)` and then potentially have a tooltip over them (exactly like the one you've done) to explain what the numbers meant. Initially it would be a mystery what the list of numbers meant, but once you'd looked at the tooltip once or twice you'd know and then you'd have them visible and useful.

Your solution hides the data so you can't see the difference between two recommendations without remembering one of the tooltips, and maybe wouldn't even think to look for it. Perhaps it doesn't matter for now, but I thought the data was sufficiently important to display it, hence my proposal.

**Comment by kenmeacham** [comment]
> > Just to be clear, the hardwired "VH", etc will be removed. The tooltip uses info directly from the domain model, e.g. "Medium", which is what you hover over.
> 
> Sorry, I understand now, and of course you provided a screenshot but for some reason I thought the tooltip was just obscuring the list of numbers - sorry. So you are removing the list of risk-level count numbers entirely because it isn't clear to the user what they mean, and replacing it with the numbers fully explained but hidden in a tooltip.
> 
> I was thinking we'd have just the list of numbers `(1/3/56/789/4567)` and then potentially have a tooltip over them (exactly like the one you've done) to explain what the numbers meant. Initially it would be a mystery what the list of numbers meant, but once you'd looked at the tooltip once or twice you'd know and then you'd have them visible and useful.
> 
> Your solution hides the data so you can't see the difference between two recommendations without remembering one of the tooltips, and maybe wouldn't even think to look for it. Perhaps it doesn't matter for now, but I thought the data was sufficiently important to display it, hence my proposal.

There is always a trade-off between showing useful information and the display getting too cluttered, which is why I suggested the tooltip on the risk level.

If we think that the risk vector info is more useful than not to display, we can display the full info as follows, instead of the tooltip.

```
Residual risk: Medium (Very Low: 695, Low: 0, Medium: 1, High: 0, Very High: 0)
```

**Comment by kenmeacham** [comment]
> > Residual risk: Medium (Very Low: 695, Low: 0, Medium: 1, High: 0, Very High: 0)
> 
> Sure, I thought you said that that made it too wide though? I guess you could put it on a new line - that could work.
> 
> ```
> Residual risk: Medium 
> (Very Low: 695, Low: 0, Medium: 1, High: 0, Very High: 0)
> ```

No, it fits on the line OK. Have implemented that now.

**Comment by scp93ch** [comment]
I had a look at the current state, and found the following issues

* In the Consequence Explorer:
  * If you click on "Calculate Attack Path" then after the calculation, the "Recommendations" button is disabled (it should not be).
  * The two buttons should be consistent in their text. Descriptions of the action are generally used on buttons, so "Get Attack Path" and "Get Recommendations" perhaps? (Briefer/simpler than "Calculate").
  * Both buttons have tooltips which are not needed (one currently provides exactly the same text as is on the button). However, I see from the code that this there in order to provide a way to tell the user to run the risk calculation first when necessary.
* In the Recommendations Explorer:
  * The link to GitHub should open in a new window.

I've fixed these things in the commit I'm just about to make (aside from removing the useless tooltip which we can live with).

**Comment by kenmeacham** [comment]
Regarding the "button inside button" error in the console, I was going to have a look at this another time. I made some fixes to resolve SonarCloud issues, but in doing so caused this console error. Unfortunately the SonarCloud issues have increased again and are now over 100 :(

**Comment by kenmeacham** [comment]
This should have been closed when 128 branch was merged into 67

**Comment by kenmeacham** [comment]
I found a small display glitch in the Recommendations Explorer, when there are no recommendations returned; an extra "0" is displayed:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/fa608067-0168-4a24-ac45-e3172bf00f07)

**Comment by kenmeacham** [comment]
Made bug fix to dev branch
