### ISSUE TITLE
Importing a system model when the domain model doesn't exist fails badly

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#16]
Scenario 1:

* system-modeller has just the "network" domain model loaded
* *normal* user tries to import a system model which uses a different domain model
* an error pop-up is shown in the browser saying "only the administrator can do that"
* clicking "ok" on the error gives a white screen

In this case, the `ModelController` checks the domain model of the system model being imported and throws an exception:

```
12:32:39.708  INFO u.a.s.i.s.s.r.ModelController:1105: User: testuser blocked from importing model with domain http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain-network-old
```

Scenario 2:

* system-modeller has just the "network" domain model loaded
* *admin* user tries to import a system model which uses a different domain model
* an error pop-up is shown in the browser saying "something went wrong, check with an administrator for further help"
* clicking "ok" on the error gives a white screen

In this case, the model is loaded in by the service but when it tries to return the updated list of models to the web client for the dashboard display it fails when trying to get the domain model for the system model:

```
java.lang.RuntimeException: Could not locate domain model for graph: http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain-network-old
        at uk.ac.soton.itinnovation.security.systemmodeller.model.Model.loadModelInfo(Model.java:395)
```

Correct behaviour:

In both cases we should provide a better error message to the client and not go to a blank screen when the error is dismissed.

**Comment by scp93ch** [comment]
We possibly can get into the same situation as scenario 2 if you delete a domain model using the knowledgebase manager page when that domain model is used by one or more system models. I don't know if there is a check for that?

**Comment by kenmeacham** [comment]
> We possibly can get into the same situation as scenario 2 if you delete a domain model using the knowledgebase manager page when that domain model is used by one or more system models. I don't know if there is a check for that?

I can confirm that this also causes problems. Basically when the user tries to list their system models, this fails due to an exception about the domain model not existing. The result is a "Something went wrong" pop-up and the user is unable to see any system models in the list.

Although this issue is related to #16, it might need a different approach to fixing, so I think it should be moved to a separate issue. I can do this, if you agree?

**Comment by kenmeacham** [comment]
Going back to the current issue (#16), I have:

1) made fixes to UI to make the error handling more resilient (avoiding the white screen)
2) fixed the server-side code so that it checks for the existence of the domain model correctly (previously it would have checked that the user has access to a non-existent domain model, thus throwing a meaningless error).

The error message displayed for the user is now as follows:

![image](https://github.com/SPYDERISK/system-modeller/assets/50845365/26082f70-125b-4b9f-8f25-ad2033217555)
