### ISSUE TITLE
Link to CONTRIBUTING in SSM UI

### ISSUE THREAD

**Issue by danshearer** [SPYDERISK/system-modeller#191]
As discussed with @kenmeacham , it would be good to link to [CONTRIBUTING.md](https://github.com/Spyderisk/system-modeller/blob/dev/CONTRIBUTING.md) in the UI. The link could be at least in "Help/About", however, the more places the better. 

For context, note that #189 will make this even better. 

Implementing these means we get to modify how we engage with would-be contributors without changing the UI. And we don't want to be like this experience:

> As is commonly the case in software development, the difficult part of this fix had nothing to do with the code itself. All of my effort was spent figuring out Ubuntu’s patch submission processes and advocating for my merge request.

which the author [reports on in great (but good) detail](https://www.downtowndougbrown.com/2024/07/i-fixed-a-6-year-old-deb-installation-bug-in-ubuntu-mate-and-xubuntu/) .

This sort of reason is why our contributor document is big on being friendly and small on making rules.

**Comment by kenmeacham** [comment]
How about an option in the Help menu to be able to report an issue, e.g.

![image](https://github.com/user-attachments/assets/8fd5b5b7-1e69-40a2-85ae-a87314c4e120)

Rather than the top-level Contributing page, maybe it could link directly to the section explaining how to create an issue:
https://github.com/Spyderisk/system-modeller/blob/dev/CONTRIBUTING.md#how-to-open-a-query-or-bug-report

CC @scp93ch
