### ISSUE TITLE
Show version and other useful info in an "About" pop-up

### ISSUE THREAD

**Issue by sjt1970** [Spyderisk/system-modeller#68]
We need to tag the SSM with proper version numbers. Often you need a specific version of SSM to make a domain model work, and you need to know both the domain model version and the SSM version. Currently we do not have version numbers of SSM so often the only thing we can do is have a "recent" SSM instance. This is AFAIK and may be incorrect in some parts, so this is a placeholder for this issue and people can correct me if wrong.

**Comment by scp93ch** [comment]
I agree. If you have access to the deployment then you can find the git commit SHA and date from the docker image metadata, but even that is not visible in the user interface.

Once we have it in the build, we could display it in a Help / About menu item in the usual way.

**Comment by scp93ch** [comment]
I think the "About" pop-up should contain:

* Spyderisk logo
* That the licence is Apache 2.0 and [link to the licence](https://github.com/Spyderisk/system-modeller/blob/dev/LICENSE.md)
* Version of the software, e.g. "v3.5.0"
* Build date/time
* Git SHA1 of the build and a link to the source code at that hash
* The version of the ssm-adaptor
* Link to https://github.com/Spyderisk
* Link to the [CONTRIBUTORS.md file](https://github.com/Spyderisk/system-modeller/blob/dev/CONTRIBUTORS.md)

To get the dynamic info we can add a new API endpoint, e.g. `/info`.
The Java system-modeller service would then retrieve the version, build date/time and SHA1 from the environment variables and return them to the client. This way we don't have to put this dynamic info into any source file (which is just awkward).

The info is already added into the metadata of the docker image build via the Dockerfile. The values are passed into the Dockerfile build via `--build-args` in the CI script ([see here](https://github.com/Spyderisk/system-modeller/blob/9999bb800d9744e0839cadcb61e6377c97d5273b/Dockerfile#L65)). It may be that they are not actually available in the environment of the docker image, in which case the Dockerfile needs to be changed to make that so, using the `ENV` command ([e.g. see here](https://github.com/Spyderisk/system-modeller/blob/9999bb800d9744e0839cadcb61e6377c97d5273b/Dockerfile#L75)).

Rather than having the service read the values directly from the environment variables, we could use the trick of defining them in `application.properties` with dummy values and then having the values overridden by the environment variables if they are set. In this way, the three keys (version, date, sha1) will always have a value so there is something to display even when you are e.g. running bootDev.

PNG logo here:

![magnifying-glass-network](https://github.com/Spyderisk/system-modeller/assets/4892991/3a490bb8-b6fe-4b85-b2b6-bcdae0efea58)

SVG source file here:

![magnifying-glass-network](https://github.com/Spyderisk/system-modeller/assets/4892991/fbed95a8-6164-4f44-927d-6d6550b37b27)

**Comment by kenmeacham** [comment]
> We need to tag the SSM with proper version numbers. Often you need a specific version of SSM to make a domain model work, and you need to know both the domain model version and the SSM version. Currently we do not have version numbers of SSM so often the only thing we can do is have a "recent" SSM instance. This is AFAIK and may be incorrect in some parts, so this is a placeholder for this issue and people can correct me if wrong.

@sjt1970 When you say "We need to tag the SSM with proper version numbers", I think you are saying that we need to be able to tag a docker image with a specific version, so that we can install this and know what we are running, yes?

Since this issue was originally created, we have improved the situation:

1) We can create a specific tagged version of an SSM docker image (e.g. v3.5.0):
https://github.com/Spyderisk/system-modeller/issues/167

2) system-modeller-deployment now has a specific version (e.g. v3.5.0) which references a tagged version of SSM:
https://github.com/Spyderisk/system-modeller-deployment/issues/16

So I think that the main requirement of this issue is already available (correct me if I'm wrong).

What is remaining (as @scp93ch was describing) is to be able to view this version info in the SSM itself, which is certainly useful for a user who is not particularly aware of which version has been deployed (e.g. on a public server).

The additional requirements of a potential "About" pop-up are somewhat more than was originally asked for, but would certainly be useful too..

**Comment by scp93ch** [comment]
You're right Ken, sorry, I subverted this issue when I should have created a new one.

I also meant to note that the ssm-adaptor version info is available at the `/system-modeller/adaptor/` endpoint so a request to that endpoint would also be needed.

**Comment by kenmeacham** [comment]
The new "About" option is available from the Help menu, as follows:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/2a839e3a-3de1-45f9-b599-cee7ddf722ff)

**Comment by kenmeacham** [comment]
The About pop-up appears as follows:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/a97e0629-64f9-4ff4-b6cf-8c47739215ef)

**Comment by danshearer** [comment]
See also #191 , Link to CONTRIBUTING in SSM UI
